### ISSUE TITLE
Day 1 objectives are not achieved by Day 1 plan

### ISSUE THREAD

**Issue by CadenceCase** [GuildCrafts/core-vanilla-javascript#32]
In solo_study.md, the Day 1 plan is to complete the Treehouse JavaScript Basics course. However, several of the Day 1 objectives are not covered in that course. (It's possible they're covered in the Stretch section -- I haven't completed those, so I'm not sure.) I'm also not sure why understanding arity is an objective. MDN indicates it's obsolete (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/arity).

Here's the Day 1 objectives list, with a note indicating whether each objective is covered in the course:

- Basic understanding of variables (YES)
- Basic string and array manipulation (strings -- YES; arrays -- NO)
- Understand 'truthy' and 'falsey' (NO)
- Understand literal notation (NO)
- Understand dot bracket notation (NO)
- Basic understanding of JSON (NO)
- Understand Operator precedence (NO)
- Practice Flow control: iteration, if, switch, while, for loops (if -- YES; all others -- NO)
- Understand and practice Functions: arguments, arity, return, scope (arguments, return, scope -- YES; arity -- NO)

**Comment by tannerwelsh** [comment]
@CadenceCase thanks a ton for submitting this excellent bug report. Really appreciate that you took the time to break it down so well.

A little backstory: an earlier version of this goal used a different course, but there was a lot of negative feedback about this course, so we switched to treehouse. (Commit https://github.com/GuildCrafts/core-vanilla-javascript/commit/966ef32523e0ae1249cfdc6e8905faff86bf2438 if you're interested). In so doing, I forgot to update the objectives list.

I've assigned this issue to myself, and will get to remedying soon. Thanks again!
